"""Add refresh_token and expires_at to SocialAccount

Revision ID: 421f4c49bec4
Revises: 87fb2a400493
Create Date: 2025-11-29 12:57:51.954028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '421f4c49bec4'
down_revision: Union[str, Sequence[str], None] = '87fb2a400493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('social_accounts', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('social_accounts', sa.Column('expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('social_accounts', 'expires_at')
    op.drop_column('social_accounts', 'refresh_token')
    # ### end Alembic commands ###
